version: '3.3'

services:
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: a7-rabbitmq
    ports: # https://www.rabbitmq.com/networking.html
      - 5672:5672 # client
      - 15672:15672 # admin
      - 61613:61613 # stomp
  redis:
    image: redis:4
    container_name: a7-redis
    ports:
      - 6379:6379
  mysql:
    image: mariadb:10.2
    container_name: a7-mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=a7
      - LANG=C.UTF-8